### ISSUE TITLE
Revert "update value type when i-score changes it" commit

### ISSUE THREAD

**Issue by theod** [OSSIA/API#13]
after some discussions with @jcelerier it seems this commit was a way to quickly solve a high level feature in i-score.

here the use case : if you declare an OSC parameter into the device explorer and then you start to write a scenario and then you realize that you need to change the type of the parameter all what have been written needs to be updated.

IHMO this an i-score issue and the API should keep strong typed Address as typing an Address is part of the specification of the ressources a scenario drive. It is like in C if you declare a int and start to code something and then you realize you need a string you'll need to review all the code to update the use of the variable. in most of the IDE you are assisted into this task so i-score should provides such high level feature to help users to update a scenario consider an Address type change.

**Comment by theod** [comment]
her his the commit to revert https://github.com/OSSIA/API/commit/abcdb2ae7b2c98b81480e29e383fb6d7936fca67

**Comment by jcelerier** [comment]
this has been reverted
