### ISSUE TITLE
use [] to access Tuple value index in Expression

### ISSUE THREAD

**Issue by theod** [OSSIA/API#17]
maybe needed to solve https://github.com/OSSIA/i-score/issues/128

**Comment by theod** [comment]
as I was working on mapping feature, I've added index feature for Destination.
does the following commit helps to solve this issue ?https://github.com/OSSIA/API/commit/613b21f765def175987da6c8182014a08de747a1

**Comment by jcelerier** [comment]
done, also with unit access
