### ISSUE TITLE
Add bracket syntax for addresses

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/API#21]
In reference to https://github.com/OSSIA/i-score/issues/128

Maybe this could be done by an attribute to the Destination class that would take a vector of ints ? (I did this in i-score)

If the vector is empty, it's the address, else we use the values in the vector to go from index to index.

e.g. something like : 

```
Destination dest("dev:/address");
dest.setAccessors({13, 5, 17}); // will fetch dev:/address[13][5][17]
```

Else it could be another type, like `TupleDestination`.

**Comment by theod** [comment]
as I was working on mapping feature, I've added index feature for Destination.
does the following commit helps to solve this issue ?https://github.com/OSSIA/API/commit/613b21f765def175987da6c8182014a08de747a1

**Comment by jcelerier** [comment]
Yep, I also added it into i-score now. Thanks !
