### ISSUE TITLE
fix test on curve

### ISSUE THREAD

**Issue by theod** [OSSIA/API#24]
there is a strange bug on Curve when trying to test valueAt for the <float, float> curve case :

QVERIFY(curveB->valueAt(-60.) == -60.); //! \note it returns 60. !
QVERIFY(curveB->valueAt(-40.) == -40.); //! \note it returns something like ~39.999... ?!?
QVERIFY(curveB->valueAt(-20.) == -20.); //! \note it returns something like ~19.999... ?!?

all the result are supposed to be made by the same formula in Curve.cpp and CurveSegmentLinear.

maybe you have an idea of what happen here @jcelerier ?

**Comment by jcelerier** [comment]
indeed : floating-point numbers are.. well.. floating-point so inexact.
See for instance http://floating-point-gui.de/errors/comparison/

Qt has a function to do the "correct" comparison for floating point values : 
http://doc.qt.io/qt-5/qtglobal.html#qFuzzyCompare

**Comment by theod** [comment]
ok thanks for the qFuzzyCompare, this is fixing the <float, float> curve case.
however I've raised another bug which seems much more tricky but certainly relative to double precision.

for a <float, int> curve from (-10., -10) point to (10., 10) point curve->valueAt(-9.) returns -8 !
the test is in CurveTest.cpp and fails as I'm expecting to get -9.

this on feature/2d_curve branch in case you have the time to look at it.

**Comment by theod** [comment]
fixed !
