### ISSUE TITLE
allow to choose to disposed or make all events of a TimeNode to happened when a first Max bound is reached

### ISSUE THREAD

**Issue by theod** [OSSIA/API#25]
this is relative to https://github.com/OSSIA/API/issues/22

**Comment by theod** [comment]
this way the MaxBoundEvent will not be optional and it will be possible to make the EndEvent and the MaxBoundEvent happened.

**Comment by theod** [comment]
I add @bltzr as he is the one who proposed this feature.

**Comment by theod** [comment]
I've renamed the issue because it is too complexe to put this property on the TimeEvent class.
see the schema I did to illustrate the problem : 

![comportement au max](https://cloud.githubusercontent.com/assets/118426/12972916/467e2cb2-d0a9-11e5-8f4b-2385d04695fc.jpg)

**Comment by theod** [comment]
the API now provide a new attribute to TimeNode to allow to dispose it when a previous timeconstriant reaches its maximal duration.

**Comment by cbossut** [comment]
This should be a condition tested against variables in the Expression.
When the max bound is reach, first activate the timeNode, then each
TimeEvent test his Expression, with the variables set according to the way
the TimeNode has been launched.

2016-02-11 11:23 GMT+01:00 theod <notifications@github.com>:

> the API now provide a new attribute to TimeNode to allow to dispose it
> when a previous timeconstriant reaches its maximal duration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OSSIA/API/issues/25#issuecomment-182793956>.
>



-- 
Clément Bossut

**Comment by theod** [comment]
after pushing this commit I've finally understood that was the same than using an expression.
so I will revert this ugly feature ! but I'll add a new one ;-)
