### ISSUE TITLE
cmake generation fails

### ISSUE THREAD

**Issue by theod** [OSSIA/API#28]
(I've sent an email but it seems my address is blocked again !)
here are some red errors returned by CMake when I try to generate the project : 

CMake Error at Implementations/Jamoma/CMakeLists.txt:10 (include):
include could not find load file:

Sanitize

CMake Error at Implementations/Jamoma/CMakeLists.txt:11 (include):
include could not find load file:

DebugMode

CMake Error at Implementations/Jamoma/CMakeLists.txt:12 (include):
include could not find load file:

UseGold

CMake Error at Implementations/Jamoma/CMakeLists.txt:13 (include):
include could not find load file:

LinkerWarnings

CMake Error at Implementations/Jamoma/CMakeLists.txt:39 (use_gold):
Unknown CMake command "use_gold".

do you have an idea of what happen here @jcelerier ?

**Comment by jcelerier** [comment]
yep !

git submodule update --init --recursive

**Comment by theod** [comment]
of course !
thanks
