### ISSUE TITLE
[pd] add range attribute

### ISSUE THREAD

**Issue by bltzr** [OSSIA/API#40]

**Comment by bltzr** [comment]
because it's cool to have min and max in i-score

**Comment by avilleret** [comment]
fixed with df888a0a948892ef88b63c905eb509d1de564c59

for now default range is from `std::numeric_limits<float>::min();` to `std::numeric_limits<float>::max();`
We should not set it when no range it specified.

**Comment by bltzr** [comment]
in Jamoma, when no range is specified, it is [0. 1.] (for decimals, i.e. floats)
I don't know if this is good but, generally speaking I think the 'convention over configuration' approach (i.e. even if not specified, there is a default) in Jamoma is good
I'm not sure I get the point of your comment, @avilleret - maybe I'm just à côté de la plaque completely

**Comment by avilleret** [comment]
I think you're completely in the center of the plaque, and I take your comment into account even if  I generally prefer to not do something user don't want (for example deciding an arbitrary range when nothing is specified)
Thanks for feedback.

**Comment by jln-** [comment]
+1

Le 17 déc. 2016 à 00:43 +0100, Antoine Villeret <notifications@github.com>, a écrit
I generally prefer to not do something user don't want (for example deciding an arbitrary range when nothing is specified)

**Comment by bltzr** [comment]
> I generally prefer to not do something user don't want (for example deciding an arbitrary range when nothing is specified)
well, that used to be my position, too... but that created a lot of problems, so we finally decided to put defaults everywhere
well, that's the whole notion of default values indeed

**Comment by bltzr** [comment]
even if, at first sight, I don't see which problem not having defaults for the range would possibly cause...

**Comment by avilleret** [comment]
yep and indeed I do choose some default for the user already
for example [ossia.parameter] default to type float if it is not specified.
And since @bltzr is my spiritual master I will follow his position and put a default range to [0..1] for float.
At last, [0..1] range will be more readable than [1.1754943508222875e-38 .. 3.4028234663852886e+38].

**Comment by bltzr** [comment]
lol

**Comment by avilleret** [comment]
And to conclude, for now there is no default bounding mode (is it the right term ?), so default range has no big consequence

**Comment by bltzr** [comment]
I was about to say the same thing, that since the default clipmode is none, that's not imposing anything to the user...
shouldn't there be a default clipmode "none" ? but that's a different issue (should I create it ?)
