### ISSUE TITLE
remove = default for StateElement, CurveAbstract and CurveSegment

### ISSUE THREAD

**Issue by theod** [OSSIA/API#6]
there are still few = default in the code that I need to remove.

**Comment by theod** [comment]
done for StateElement

**Comment by theod** [comment]
I tried to revive = default into CurveSegment without success on fix/remove_default branch.
@jcelerier could you have a look to what is going wrong ?

**Comment by jcelerier** [comment]
Ah, it's not a problem for CurveSegment because templates handle this properly. It's only for non-template base classes.

**Comment by theod** [comment]
ok ! so I need to do it for CurveAbstract but not for CurveSegment that's it ?

**Comment by jcelerier** [comment]
yup
