### ISSUE TITLE
Expected behaviour of triggers when triggered by happen()

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/API#9]
Hi,

What should happen when `happen()`is called on a time node ? 

On i-score this seems to trigger every condition, including the ones that are false. However when the trigger is activated from outside, via a osc message, the false conditions are correctly not executed. I think that this is the behaviour that one expects when triggering a trigger manually from i-score, but I don't know how to do it.

Thanks!

**Comment by theod** [comment]
for now TimeNode::happen() is a simply calling TimeEvent::happen() on all time events of the time node.
I propose to remove TimeNode::happen() and TimeNode::dispose() to replace it by something like TimeNode::trigger()where Expression will be evaluated to make events to happen or to dispose them.

does it sounds good for you ?

**Comment by jcelerier** [comment]
I think that happen() can stay: maybe it will be useful if somebody wants to debug his scenario (we can add a checkbox in i-score to choose between the two behaviours easily).

**Comment by theod** [comment]
but this sounds like a high level feature from API point of view as if you want to force a condition to be true or false the solution would to replace expression by ExpressionTrue or ExpressionFalse.
this way you can manage any kind of configuration to test them while this happen() method would provide a kind of way to make them all to True and it sounds strange to provide such a feature at the API level IHMO.

by the way I have added the trigger method but no way to build i-score (I've sent you an email to describe the trouble)

**Comment by theod** [comment]
I close this issue
